import os
import re
from pathlib import Path


OUTPUT = Path(__file__).resolve().parents[1] / "core" / "build_info.py"


def main() -> None:
    source_commit = os.environ.get("GITHUB_SHA", "local").strip()
    if source_commit != "local" and not re.fullmatch(r"[0-9a-fA-F]{7,64}", source_commit):
        raise RuntimeError("GITHUB_SHA is not a valid hexadecimal commit identifier")

    OUTPUT.write_text(
        '"""Build identity generated by CI before packaging."""\n\n'
        f'SOURCE_COMMIT = "{source_commit.lower()}"\n',
        encoding="utf-8",
    )
    print(f"Prepared Windows build identity: {source_commit[:12]}")


if __name__ == "__main__":
    main()
